WEB/Areas/Clients/Controllers/ClientsConsultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

using WEB.AppInfra.Cookies.Service;
using WEB.AppInfra.Security.Filters;
using WEB.AppInfra.Security.SessionUserConfiguration;
using WEB.AppStart.AppSettingsMappers.Extensions;
using WEB.AppStart.AppSettingsMappers.Unities;
using WEB.Controllers;

namespace WEB.Areas.Clients.Controllers {

    [Area("Clients")]
    public class ClientsConsultController : RestrictController {
        private CookieServices CookiesServices;
        private IConfiguration Configuration;

        private readonly SessionUser         SessionUser;
        private readonly DataBaseSettings    DataBaseSettings;
        private readonly ApiServicesSettings ApiServicesSettings;

        public ClientsConsultController(CookieServices _ICookieServices,
                                         SessionUser    _SessionUser,
                                         IConfiguration _IConfiguration) {

            CookiesServices = _ICookieServices;
            SessionUser     = _SessionUser;
            Configuration   = _IConfiguration;

            DataBaseSettings    = Configuration.GetSectionMapped<DataBaseSettings>();
            ApiServicesSettings = Configuration.GetSectionMapped<ApiServicesSettings>();
        }

        public IActionResult Index() {
            return RedirectToAction("ListClients");
        }

        [HttpGet, ServiceFilter(typeof (LoggedAccess))]
        public IActionResult ListClients() {

            return View();
        }
    }
}

WEB/Areas/Orders/Controllers/OrdersOperationController.cs
using System;

using DAL.Models.Orders.Services.Contracts;

using Microsoft.AspNetCore.Mvc;

using WEB.Areas.Orders.Models.Forms;
using WEB.Controllers;

namespace WEB.Areas.Orders.Controllers {

    [Area("Orders")]
    public class OrdersOperationController : RestrictController {

        private readonly IOrderServicesDAL _orderServicesDAL;

        public OrdersOperationController(IOrderServicesDAL orderServicesDAL) {
            _orderServicesDAL = orderServicesDAL;
        }

        public IActionResult Index() {
            var Form = new RegisterOrderForm() {};

            return View(Form);
        }

    }

}

WEB/Areas/Products/Controllers/ProductsConsultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

using WEB.AppInfra.Cookies.Service;
using WEB.AppInfra.Security.Filters;
using WEB.AppInfra.Security.SessionUserConfiguration;
using WEB.AppStart.AppSettingsMappers.Extensions;
using WEB.AppStart.AppSettingsMappers.Unities;
using WEB.Areas.Products.Models.ViewModels;
using WEB.Controllers;

namespace WEB.Areas.Products.Controllers {

    [Area("Products")]
    public class ProductsConsultController : RestrictController {
        private CookieServices CookiesServices;
        private IConfiguration Configuration;

        private readonly SessionUser         SessionUser;
        private readonly DataBaseSettings    DataBaseSettings;
        private readonly ApiServicesSettings ApiServicesSettings;

        public ProductsConsultController(CookieServices _ICookieServices,
                                         SessionUser    _SessionUser,
                                         IConfiguration _IConfiguration) {

            CookiesServices = _ICookieServices;
            SessionUser     = _SessionUser;
            Configuration   = _IConfiguration;

            DataBaseSettings    = Configuration.GetSectionMapped<DataBaseSettings>();
            ApiServicesSettings = Configuration.GetSectionMapped<ApiServicesSettings>();
        }

        public IActionResult Index() {
            return RedirectToAction("ListProducts");
        }

        [HttpGet, ServiceFilter(typeof (LoggedAccess))]
        public IActionResult ListProducts() {

            return View();
        }
    }
}

WEB/Areas/Start/Controllers/PrivacyController.cs
using System.Extensions;

using Microsoft.AspNetCore.Mvc;

using WEB.AppInfra.Cookies.Service;
using WEB.AppInfra.Security.Filters;
using WEB.Areas.Start.Models.ViewModels;
using WEB.Controllers;

namespace WEB.Areas.Start.Controllers {

    [Area("start")]
    public class PrivacyController : RestrictController {

        private CookieServices CookieServices;
        public PrivacyController(CookieServices _ICookieServices) {
            
            CookieServices = _ICookieServices;
        }
        
        public IActionResult Index() {
            return RedirectToAction("PrivacyDetails");
        }

        public IActionResult PrivacyDetails() {
            return View();
        }

        public IActionResult PartialCookieConsent() {
            var ViewModel = new CookieConsentVM();
            
            var cookie = CookieServices.Read("Consent");

            if (cookie.IsEmpty()) {
                ViewModel.showBanner = true;
            } 
            
            return View(ViewModel);
        }
        
        public IActionResult registerCookieConsent(string option) {
            CookieServices.Write("Consent", option);
            
            return Json(new { message = "Opçao de consentimento de cookies registrada!!" });
        }
    }
}

WEB/Views/Shared/masterpage.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            @(ViewBag.Title == null ? "Tpz System" : ViewBag.Title)
        </title>
    
        <link rel="stylesheet" type="text/css" href="~/Areas/Start/assets/css/">
        <link rel="stylesheet" type="text/css" href="~/Assets/css/system-style.css">
        <link rel="stylesheet" type="text/css" href="~/Assets/lib/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="~/Assets/lib/fontawesome-free-5/css/all.min.css">
        <link rel="stylesheet" type="text/css" href="~/Assets/lib/jquery-toast-plugin/jquery.toast.min.css">
        
        @RenderSection("Styles", required: false)
    </head>
    
    <body>
        <main id="main" class="row">
            @*@Html.ContentLoad("box-cookie-consent", Url.Action("PartialCookieConsent", "Privacy", new { area = "Start" }))*@
            
            <header id="topo-sistema" class="col-12">
                @{ Html.RenderPartial("partial-topo-sistema"); }
            </header>
            
            <aside id="menu-lateral-sistema" class="col-3">
                @{ Html.RenderPartial("partial-lateral-menu"); }
            </aside>
            
            <article id="conteudo-sistema" class="col-9">
                @RenderBody()
            </article>
        </main>
    </body>
        
    <!--Setor de scripts do sistema-->
    <script type="text/javascript" src="~/Assets/lib/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/Assets/lib/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Assets/lib/fontawesome-free-5/js/all.js"></script>
    <script type="text/javascript" src="~/Assets/lib/gasparesganga-jquery-loading-overlay/loadingoverlay.js"></script>
    <script type="text/javascript" src="~/Assets/lib/jquery-toast-plugin/jquery.toast.min.js"></script>
    <script type="text/javascript" src="~/Assets/js/system.js"></script>
    
    @RenderSection("Scripts", required: false)
    <!--fim Setor de scripts do sistema-->

</html>

WEB/Views/Shared/partial-lateral-menu.cshtml
<div id="accordion">
    <div class="card item-menu">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <a class="" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Dados Auxiliares
                </a>
            </h5>
        </div>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body sub-item">
                <a href="@Url.Action("ListProviders", "ProvidersConsult", new { area="Providers" })" class="sub-item">
                    Fornecedores
                </a>
            </div>
            <div class="card-body sub-item ">
                <a href="@Url.Action("ListProducts", "ProductsConsult", new { area = "Products" } )" class="sub-item">
                    Produtos
                </a>
            </div>
            <div class="card-body sub-item ">
                <a href="@Url.Action("Index", "ClientsConsult", new { area = "Clients" } )" class="sub-item">
                    Clientes
                </a>
            </div>
        </div>
    </div>
    
    <div class="card item-menu">
        <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
                <a class="" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Pedidos
                </a>
            </h5>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body sub-item">
                <a href="@Url.Action("Index", "OrdersOperation", new { area = "Orders" })" class="sub-item">Efetuar Novo Pedido</a>
            </div>
            <div class="card-body sub-item ">
                <a href="" class="sub-item">Historico</a>
            </div>
        </div>
    </div>
</div>

WEB/Views/Shared/partial-topo-sistema.cshtml
<div class="logo">
    <h2>
        <span>TPZ SYSTEM</span>
        <span class="logo_mini">T</span>
    </h2>
</div>
<div class="user">
    @*<span>
        Ramon C. 
        <i class="fas fa-angle-down icon-arrow"></i>
    </span>
    <div class="menu_user">
        <ul>
            <li>
                <a href="#">
                    <i class="fas fa-cog"></i>
                    Opções
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-sign-out-alt"></i>
                    Sair
                </a>
            </li>
        </ul>
    </div>*@
</div>